name: CI Build Status

on:
  # Triggers the workflow on push events to the 'main' branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Simple Success Check
        # This step will always pass (exit code 0), ensuring the workflow is green
        run: echo "CI check passed successfully!"
